name: CI

on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run: echo "Hello world from test"
    
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run: echo "Hello world from deploy"
